name: Build for MacOS M1
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: if grep -Fxq "devel" cmd/go2tv/version.txt;then echo "GO2TV_VERSION=$(cat cmd/go2tv/version.txt)";else echo "GO2TV_VERSION=v$(cat cmd/go2tv/version.txt)";fi  >> $GITHUB_ENV

    - uses: WillAbides/setup-go-faster@v1.7.0
      id: setup-go-faster
      with:
        go-version: "*"

    - name: Get dependencies
      run: sudo apt update && sudo apt install xorg-dev

    - name: Install fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Install fyne-cross
      run: go install github.com/fyne-io/fyne-cross@latest

    - name: Package (macOS)
      run:  fyne-cross darwin -arch=arm64 -icon assets/go2tv-icon-desktop.png -app-id "com.alexballas.go2tv" ./cmd/go2tv/

    - name: Prepary app for packaging
      run:  mv fyne-cross/dist/darwin-arm64/go2tv.app .

    - uses: actions/upload-artifact@v2
      with:
        name: go2tv_${{ env.GO2TV_VERSION }}_macOS_arm64
        path: |
          LICENSE
          README.md
          go2tv.app
        retention-days: 2
