name: Build for ARMv6 (32-bit)
on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: if grep -Fxq "devel" version.txt;then echo "GO2TV_VERSION=$(cat version.txt)";else echo "GO2TV_VERSION=v$(cat version.txt)";fi  >> $GITHUB_ENV

    - uses: pguyot/arm-runner-action@v2
      id: main_image
      with:
        copy_repository_path: /go2tv_dir
        copy_artifact_path: go2tv
        image_additional_mb: 4096
        base_image: raspios_lite:latest
        commands: |
            cd /
            df -h
            sudo apt update
            sudo apt install -y xorg-dev
            sudo apt clean
            sudo rm -rf /var/lib/apt/lists/*
            wget -nv https://go.dev/dl/go1.25.1.linux-armv6l.tar.gz
            tar -xzf go1.25.1.linux-armv6l.tar.gz
            rm go1.25.1.linux-armv6l.tar.gz
            export GOROOT=/go
            cd /go2tv_dir
            /go/bin/go build -tags migrated_fynedo -ldflags "-s -w -X main.version=$(echo ${{ env.GO2TV_VERSION }} | sed 's/^v//')" -o go2tv cmd/go2tv/go2tv.go

    - uses: actions/upload-artifact@v4
      with:
        name: go2tv_${{ env.GO2TV_VERSION }}_linux_arm
        path: |
          LICENSE
          README.md
          go2tv
        retention-days: 2
