name: Build for ARM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: if grep -Fxq "devel" cmd/go2tv/version.txt;then echo "GO2TV_VERSION=$(cat cmd/go2tv/version.txt)";else echo "GO2TV_VERSION=v$(cat cmd/go2tv/version.txt)";fi  >> $GITHUB_ENV

    - uses: pguyot/arm-runner-action@v2
      id: main_image
      with:
        copy_repository_path: /go2tv_dir
        copy_artifact_path: go2tv
        image_additional_mb: 800
        commands: |
            cd /
            sudo apt update
            sudo apt install -y xorg-dev libgles-dev
            sudo apt clean
            wget -nv https://go.dev/dl/go1.19.linux-armv6l.tar.gz
            tar -xzf go1.19.linux-armv6l.tar.gz
            rm go1.19.linux-armv6l.tar.gz
            export GOROOT=/go
            cd /go2tv_dir
            /go/bin/go build -ldflags "-s -w" -o go2tv cmd/go2tv/go2tv.go
            
    - uses: actions/upload-artifact@v2
      with:
        name: go2tv_${{ env.GO2TV_VERSION }}_linux_arm
        path: |
          LICENSE
          README.md
          go2tv
        retention-days: 2
